#!/usr/bin/env python3
"""Export the compose training pool to LLaMA-Factory format with a SHAPE-level
A/B split for the compositional-generalisation test.

Split discipline:
- B (held-out) = (a) ALL rows whose shape signature is rooted in keys_where
  (grouped-compare construction — designated strict holdout, mirrors probe C5),
  plus (b) a deterministic ~20%% of remaining shape signatures (whole shapes move
  together). A = everything else.
- The probe's C3 construction (setop.difference over values with a NOT pred)
  is never generated by the recipe engine, so probe-C3 remains a generator-level
  strict holdout on top of B.
- Training prompt is byte-identical to the eval prompt (run_compose_probe_eval
  SYSTEM_PROMPT): train distribution == serve distribution.
- ~5%% abstain rows (out-of-grammar templates: median/percentile/stddev/trend)
  teach the abstain channel, which degraded under guided decoding (2/12).

Usage: .venv/bin/python scripts/export_compose_sft.py [--pool data/qa/compose_train_v1/pool.jsonl]
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import random
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

_spec = importlib.util.spec_from_file_location("drv", ROOT / "scripts/run_compose_probe_eval.py")
drv = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(drv)
SYSTEM_PROMPT = drv.SYSTEM_PROMPT


def _abstain_rows(rng: random.Random, n: int) -> list[dict]:
    years = list(range(2022, 2027))
    cats = ["goods", "services", "works"]
    makers = [
        lambda: (f"What is the median contract value of {rng.choice(cats)} notices published in {rng.choice(years)}?",
                 "median is an order statistic; not expressible in this algebra"),
        lambda: (f"What is the 90th percentile of contract values for notices published in {rng.choice(years)}?",
                 "percentiles are order statistics; not expressible in this algebra"),
        lambda: (f"Did the yearly number of {rng.choice(cats)} notices increase every single year from 2022 to {rng.choice([2024, 2025, 2026])}?",
                 "requires a sequence predicate over ordered groups; not expressible"),
        lambda: (f"What is the standard deviation of contract values in the {rng.choice(cats)} category?",
                 "standard deviation is not expressible in this algebra"),
        lambda: (f"What was the average time between publication and award signing for notices in {rng.choice(years)}?",
                 "date arithmetic between fields is not expressible in this algebra"),
    ]
    rows, seen, attempts = [], set(), 0
    # the template space is small (~40 distinct questions); attempts-bounded so
    # the loop terminates when the space is exhausted before the quota
    while len(rows) < n and attempts < 50 * max(1, n):
        attempts += 1
        q, reason = rng.choice(makers)()
        if q in seen:
            continue
        seen.add(q)
        rows.append({"id": f"CTA::{len(rows):04d}", "question": q,
                     "output": {"abstain": True, "reason": reason},
                     "shape_signature": "ABSTAIN"})
    return rows


def _old_task_rows(rng: random.Random, cap_per_family: int = 150) -> list[dict]:
    """OLD benchmark questions rendered in the NEW algebra: train-split gold
    plans translated by the regression-validated converter (100% on final_test).
    Keeps the new adapter bilingual in task types, not just in new compositions.
    Family caps mirror the main-ladder exporter's anti-prior discipline."""
    from procurement_graph.compose.from_gold import Unsupported, gold_plan_to_tree

    rows, per_family = [], Counter()
    with (ROOT / "data/qa/cicada_core_v4/train.jsonl").open() as fh:
        candidates = [json.loads(line) for line in fh]
    rng.shuffle(candidates)
    for row in candidates:
        if row.get("expected_status") != "answerable":
            continue
        family = str((row.get("gold_plan") or {}).get("metadata", {}).get("template_family")
                     or row.get("template_family") or "?")
        if per_family[family] >= cap_per_family:
            continue
        try:
            tree = gold_plan_to_tree(row)
        except Unsupported:
            continue
        per_family[family] += 1
        rows.append({"id": "CTO::" + row["id"], "question": row["question"],
                     "tree": tree, "shape_signature": "OLD:" + family})
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pool", default="data/qa/compose_train_v1/pool.jsonl")
    ap.add_argument("--holdout-frac", type=float, default=0.2)
    ap.add_argument("--seed", type=int, default=20260710)
    ap.add_argument("--out-dir", default="data/training/llamafactory_compose_v1")
    ap.add_argument("--old-cap", type=int, default=150,
                    help="per-family cap for translated old-benchmark rows (0 disables)")
    ap.add_argument("--order-twins", type=float, default=0.0,
                    help="fraction of A rows duplicated with a reordered-clause surface")
    ap.add_argument("--holdout-out", default="data/qa/compose_train_v1/holdout_B.jsonl")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    rows = [json.loads(line) for line in (ROOT / args.pool).open()]
    shapes = sorted({r["shape_signature"] for r in rows})

    def held_out(sig: str) -> bool:
        # v2 strict construction holdout rotated: keys_where is now TRAINED
        # (C5 lesson); setop.intersect held out instead — union/difference are
        # demonstrated, intersect tests within-family construction transfer.
        if sig.startswith("setop.intersect"):
            return True
        h = int(hashlib.sha1(sig.encode()).hexdigest(), 16) % 1000
        return h < args.holdout_frac * 1000

    a_rows = [r for r in rows if not held_out(r["shape_signature"])]
    b_rows = [r for r in rows if held_out(r["shape_signature"])]
    a_shapes = {r["shape_signature"] for r in a_rows}
    b_shapes = {r["shape_signature"] for r in b_rows}
    assert not (a_shapes & b_shapes), "shape leak between A and B"

    old_rows = _old_task_rows(rng, args.old_cap) if args.old_cap else []
    abstain = _abstain_rows(rng, max(1, (len(a_rows) + len(old_rows)) // 20))

    # order twins: same tree + answer, second surface with clause runs reversed
    # (meaning-preserving, side-safe). Teaches order invariance pairwise.
    twins = []
    if args.order_twins > 0:
        import re
        cl = re.compile(r"(?<=notices )[^;?.]+(?:; [^;?.]+)+")
        def reorder(q: str) -> str:
            def flip(m):
                return "; ".join(reversed(m.group(0).split("; ")))
            return " than ".join(cl.sub(flip, side, count=1) for side in q.split(" than "))
        for r in a_rows:
            if rng.random() >= args.order_twins:
                continue
            q2 = reorder(r["question"])
            if q2 != r["question"]:
                twins.append({**r, "question": q2})

    def to_lf(row) -> dict:
        output = row.get("output") or {"tree": row["tree"]}
        return {"system": SYSTEM_PROMPT, "instruction": row["question"], "input": "",
                "output": json.dumps(output, separators=(",", ":"))}

    train = ([to_lf(r) for r in a_rows] + [to_lf(r) for r in twins]
             + [to_lf(r) for r in old_rows] + [to_lf(r) for r in abstain])
    rng.shuffle(train)
    val = train[: max(16, len(train) // 50)]
    train = train[len(val):]

    out = ROOT / args.out_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "compose_sft_train.json").write_text(json.dumps(train, indent=0))
    (out / "compose_sft_val.json").write_text(json.dumps(val, indent=0))
    (out / "dataset_info.json").write_text(json.dumps({
        "compose_sft_train": {"file_name": "compose_sft_train.json",
                              "columns": {"system": "system", "prompt": "instruction",
                                          "query": "input", "response": "output"}},
        "compose_sft_val": {"file_name": "compose_sft_val.json",
                            "columns": {"system": "system", "prompt": "instruction",
                                        "query": "input", "response": "output"}},
    }, indent=1))
    # B set exported as an eval file in probe format (id/question/oracle/tree)
    b_eval = [{"id": r["id"], "template_family": "B:" + r["shape_signature"][:40],
               "distance_band": "B_holdout", "question": r["question"],
               "expected_status": "answerable", "answer_type": r["answer_type"],
               "oracle_answer": r["answer"], "compose_tree": r["tree"],
               "benchmark": "compose_train_v1_B"} for r in b_rows]
    b_path = ROOT / args.holdout_out
    with b_path.open("w") as fh:
        for r in b_eval:
            fh.write(json.dumps(r, default=str) + "\n")

    print(f"pool {len(rows)} rows / {len(shapes)} shapes")
    print(f"A(train): {len(a_rows)} rows / {len(a_shapes)} shapes "
          f"(+{len(twins)} order twins, +{len(old_rows)} old-task translated, +{len(abstain)} abstain)")
    print(f"B(holdout): {len(b_rows)} rows / {len(b_shapes)} shapes -> {b_path}")
    print(f"train/val: {len(train)}/{len(val)} -> {out}")
    kw = sum(1 for r in b_rows if r["shape_signature"].startswith("keys_where"))
    print(f"B strict keys_where rows: {kw}")
    print("B shape count by root:", dict(Counter(s.split("(")[0] for s in b_shapes)))


if __name__ == "__main__":
    main()
